export const GET_ERRORS = "GET_ERRORS";
export const GET_TICKETBOOKINGS = "GET_TICKETBOOKINGS";
export const GET_TICKETBOOKING = "GET_TICKETBOOKING";
export const DELETE_TICKETBOOKING = "DELETE_TICKETBOOKING";